// 开发者模式「参数旋钮」元数据表（纯数据，无逻辑）。
// 用途：给开发者模式渲染约 45 项后端 config 参数的可调 UI。
// 数据来源：结构/默认值取自 src/config.ts；大白话文案复用盘点输出（task w90r4pduf）。
// 注意：这是展示层元数据，不替换后端 config；改后端 config 对象的字段才即时生效。
//
// 每项字段说明：
//   path    - 对应 config 里的路径（嵌套对象/record 的每个子键各占一条）
//   label   - 短中文标题
//   hint    - 一句大白话 + 括注调大/调小效果
//   group   - 分组名（前端好分块显示）
//   control - 控件类型：slider | number | toggle | tags | readonly
//   min/max/step - 数值项的滑块范围（从盘点建议范围合理推）
//   options - tags/select 项的可选值数组

export const CONFIG_META = [
  // ===== identity（身份，只读）=====
  {
    path: 'identity.subjectId',
    label: '记忆归属 ID',
    hint: '这本记忆属于谁的标识；v1 恒为 owner，改了等于换一个人的记忆空间（本版只读，不建议改）。',
    group: 'identity',
    control: 'readonly',
  },
  {
    path: 'identity.hostId',
    label: '宿主环境 ID',
    hint: '这套记忆跑在哪个环境的标识；v1 恒为 testbench，多宿主时用来区分来源（本版只读）。',
    group: 'identity',
    control: 'readonly',
  },

  // ===== privacy（隐私）=====
  {
    path: 'privacyMode',
    label: '隐私总开关',
    hint: '开了以后新证据默认不上云端模型（更安全，但画像/归因可能变弱）；关了证据默认可上云（效果更好但隐私敞开）。',
    group: 'privacy',
    control: 'toggle',
  },
  {
    path: 'evidenceDefaults.allowLocalRead',
    label: '新证据·本地可读',
    hint: '新证据默认允不允许本地读取；开=正常参与画像/召回，关=连本地都不读几乎等于白记。',
    group: 'privacy',
    control: 'toggle',
  },
  {
    path: 'evidenceDefaults.allowInference',
    label: '新证据·可推画像',
    hint: '新证据默认允不允许拿来推结论；开=画像更丰满，关=只存不推、画像更空。',
    group: 'privacy',
    control: 'toggle',
  },
  {
    path: 'observedDefaults.allowLocalRead',
    label: '行为观察·本地可读',
    hint: '「系统偷看到的行为」证据本地能不能读；开=参与召回/归因，关=等于白观察。',
    group: 'privacy',
    control: 'toggle',
  },
  {
    path: 'observedDefaults.allowCloudRead',
    label: '行为观察·可上云',
    hint: '偷看到的行为默认允不允许喂云端模型；开=效果更好但更敏感，关（现值）=不外传最保守。',
    group: 'privacy',
    control: 'toggle',
  },
  {
    path: 'observedDefaults.allowInference',
    label: '行为观察·可推画像',
    hint: '行为观察默认允不允许拿来推结论；开=行为可推假设（如常熬夜→推作息），关=只记不推。',
    group: 'privacy',
    control: 'toggle',
  },

  // ===== workingMemory（回话窗口）=====
  {
    path: 'workingMemory.maxTurns',
    label: '回话带几轮原文',
    hint: '回话时手边摊着最近几轮对话原文；调大=上下文更连贯但更慢更费 token，调小=省钱更快但容易刚说就忘。',
    group: 'workingMemory',
    control: 'slider',
    min: 1,
    max: 20,
    step: 1,
  },

  // ===== retrieval（召回）=====
  {
    path: 'retrieval.topK',
    label: '回话注入几条认知',
    hint: '每次回话最多翻出几张最相关的知识卡；调大=更懂你但噪声/token 涨，调小=干净省钱但可能漏事。',
    group: 'retrieval',
    control: 'slider',
    min: 1,
    max: 15,
    step: 1,
  },
  {
    path: 'retrieval.minEffectiveConfidence',
    label: '注入的最低有效置信',
    hint: '衰减后有效置信低于此门槛就不注入（千分制同一把尺）；调高=只让很有把握的进来但可能太保守，调低=半信半疑也塞进来但易带过气结论。',
    group: 'retrieval',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },

  // ===== consolidation（画像把握度算法）=====
  {
    path: 'consolidation.baseByFormedBy.stated',
    label: '起步分·亲口说的',
    hint: '「用户亲口说的」认知起步分（千分制，最可信）；调高=更快被当定论，调低=你说的也要多攒证据才算数。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.baseByFormedBy.observed',
    label: '起步分·观察到的',
    hint: '「系统观察到的行为」认知起步分；调高=光靠观察也易被当真、可能过度解读，调低=观察要更多印证才算数。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.baseByFormedBy.ruled',
    label: '起步分·规则推的',
    hint: '「按规则推出来的」认知起步分（介于说和推之间）；调高=规则推断更受信任，调低=更需佐证。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.baseByFormedBy.inferred',
    label: '起步分·模型脑补的',
    hint: '「模型推测出来的」认知起步分（最不可靠）；调高=脑补更易被当真、画像丰富但风险大，调低=脑补一律低声说更稳但偏空。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.supportStep',
    label: '每条支持证据加分',
    hint: '每多一个人作证可信度往上抬多少；调高=证据一多把握度涨得快，调低=攒再多也涨得慢很保守。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 200,
    step: 5,
  },
  {
    path: 'consolidation.supportCap',
    label: '支持证据封顶条数',
    hint: '支持证据最多算几条、防刷同类堆高；调高=允许更多累加上限更高，调低=很快封顶防刷但可能压住真确定的事。',
    group: 'consolidation',
    control: 'slider',
    min: 1,
    max: 15,
    step: 1,
  },
  {
    path: 'consolidation.contradictPenalty',
    label: '每条反对证据扣分',
    hint: '有人反驳时可信度往下掉多少（现值一条抵三条支持）；调高=对矛盾很敏感易翻案，调低=结论更顽固不易被推翻。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 300,
    step: 10,
  },
  {
    path: 'consolidation.minConfidence',
    label: '把握度地板值',
    hint: '把握度永远不低于这个数（恒 >0）；调高=再没谱的也保底较高分可能虚高，调低=垫底认知可接近 0 更拉得开差距。',
    group: 'consolidation',
    control: 'slider',
    min: 1,
    max: 300,
    step: 5,
  },
  {
    path: 'consolidation.credThresholds.stable',
    label: '「稳定」档门槛',
    hint: '达到这个分才算最可信的稳定档（需 > 有限档）；调高=更难升稳定、系统嘴更严，调低=易评稳定、更自信但可能过早下定论。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.credThresholds.limited',
    label: '「有限置信」档门槛',
    hint: '达到这个分算中等可信的有限档（需 低 < 有限 < 稳定）；调高=更多认知被压到低置信/候选，调低=容易进有限档。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.credThresholds.low',
    label: '「低置信」档门槛',
    hint: '达到这个分算低置信、不到就是候选（需 < 有限）；调高=更多东西掉进候选、系统更爱说「我猜」，调低=候选更少。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'consolidation.transientTypes',
    label: '临时类型清单',
    hint: '哪些类型算「临时内容」（置信封顶、永不进稳定/有限档）；加进来=更多类型被当临时对待，清空=可能把一时情绪当长期特质。',
    group: 'consolidation',
    control: 'tags',
    options: ['state', 'hypothesis', 'trend', 'goal', 'project', 'trait', 'fact', 'preference'],
  },
  {
    path: 'consolidation.transientCap',
    label: '临时类置信封顶',
    hint: '情绪等临时内容最多攒到多少分（建议 ≤ 低置信门槛）；调高=情绪也能攒高分可能被长期化，调低=始终很低几乎只当候选看。',
    group: 'consolidation',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },

  // ===== attribution（M4 归因）=====
  {
    path: 'attribution.windowHours',
    label: '归因回看小时数',
    hint: '归因时往回看多少小时找线索（如抱怨「昨晚没睡好」回看 24h）；调大=能捞更早的因但易扯上旧事，调小=精准但可能漏稍早真因。',
    group: 'attribution',
    control: 'slider',
    min: 1,
    max: 72,
    step: 1,
  },
  {
    path: 'attribution.hypothesisCap',
    label: '假设置信封顶',
    hint: '归因产出的假设把握度封顶（假设只敢低声说，建议 ≤ 低置信门槛）；调高=假设更笃定可能把猜测说成结论，调低=永远心虚更保守。',
    group: 'attribution',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'attribution.maxPhenomenaPerRun',
    label: '一次归因几个现象',
    hint: '一次最多解释几个「最近没归过因的现象」；调大=一次解释多个但易产出成堆不靠谱假设，设 1（现值）=只盯当下一件最克制。',
    group: 'attribution',
    control: 'slider',
    min: 1,
    max: 5,
    step: 1,
  },
  {
    path: 'attribution.maxCausesPerHypothesis',
    label: '单假设最多挂几因',
    hint: '单条假设最多挂几条原因证据（防乱挂无关证据虚撑）；调大=解释更全但易掺无关证据，调小=每假设只挂最相关的干净但可能漏因。',
    group: 'attribution',
    control: 'slider',
    min: 1,
    max: 5,
    step: 1,
  },
  {
    path: 'attribution.minPhenomenonSupport',
    label: '现象归因最少支撑',
    hint: '现象要反复出现 ≥N 条支撑才归因（治脑补）；调大=极稳但反应迟钝可能错过真问题，设 1=偶发一次就归因灵敏但爱脑补。',
    group: 'attribution',
    control: 'slider',
    min: 1,
    max: 5,
    step: 1,
  },

  // ===== asking（M5 主动询问）=====
  {
    path: 'asking.maxAsks',
    label: '一轮最多问几个',
    hint: '一轮最多主动问用户几个问题（0=关闭主动问）；调大=追问快但打扰多，设 1（现值）=最不烦人。',
    group: 'asking',
    control: 'slider',
    min: 0,
    max: 3,
    step: 1,
  },
  {
    path: 'asking.confidenceBand.min',
    label: '发问置信下限',
    hint: '只问把握度不低于此下限的假设（需 < 上限）；调高=只问较有谱的但问得少，调低=纯瞎猜也拿去问、易问些莫名其妙的。',
    group: 'asking',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'asking.confidenceBand.max',
    label: '发问置信上限',
    hint: '只问把握度不高于此上限的假设（需 > 下限）；调高=连相当确定的也去确认啰嗦但严谨，调低=只问很不确定的。',
    group: 'asking',
    control: 'slider',
    min: 0,
    max: 1000,
    step: 10,
  },
  {
    path: 'asking.askableStatuses',
    label: '可发问的可信档',
    hint: '只对这些可信档的假设发问（默认只问候选/低置信）；加档（如 limited）=连中等把握也去问问得更多，缩档=问得最少。',
    group: 'asking',
    control: 'tags',
    options: ['candidate', 'low', 'limited', 'stable'],
  },

  // ===== profileUpdate（画像更新触发）=====
  {
    path: 'profileUpdate.batchSize',
    label: '攒几条对话更新',
    hint: '攒够 N 条新对话才排一次画像更新（治勤）；调大=省算力但画像更新更滞后，调小=聊几句就更新新鲜但费算力。',
    group: 'profileUpdate',
    control: 'slider',
    min: 1,
    max: 30,
    step: 1,
  },
  {
    path: 'profileUpdate.idleMinutes',
    label: '空闲几分钟更新',
    hint: '空闲这么多分钟没新消息就更新一次（与攒批先到先触发）；调大=要歇很久才触发更新更少，调小=稍歇一会就更新更勤。',
    group: 'profileUpdate',
    control: 'slider',
    min: 1,
    max: 120,
    step: 1,
  },

  // ===== background（周期后台·分型衰减/过期/趋势）=====
  {
    path: 'background.halfLifeDays.state',
    label: '半衰期·情绪状态',
    hint: '情绪 state 多少天淡一半（现值 1.5，忘得最快）；调大=昨天坏心情还压着今天，调小=情绪淡得飞快很快当没发生。',
    group: 'background',
    control: 'slider',
    min: 0.5,
    max: 30,
    step: 0.5,
  },
  {
    path: 'background.halfLifeDays.hypothesis',
    label: '半衰期·假设',
    hint: '假设多少天没新印证淡一半（现值 2，忘得快）；调大=旧假设留得久可能拿过气猜测说事，调小=没及时印证很快作废。',
    group: 'background',
    control: 'slider',
    min: 0.5,
    max: 60,
    step: 0.5,
  },
  {
    path: 'background.halfLifeDays.goal',
    label: '半衰期·目标',
    hint: '目标多少天淡一半（现值 14，忘得慢）；调大=长期陪伴感强但可能抱着早放弃的目标不放，调小=不常提的很快淡出。',
    group: 'background',
    control: 'slider',
    min: 1,
    max: 180,
    step: 1,
  },
  {
    path: 'background.halfLifeDays.project',
    label: '半衰期·项目',
    hint: '项目多少天淡一半（现值 14，忘得慢）；调大=项目记得更久，调小=久不提的项目快速淡出。',
    group: 'background',
    control: 'slider',
    min: 1,
    max: 180,
    step: 1,
  },
  {
    path: 'background.halfLifeDays.trend',
    label: '半衰期·趋势',
    hint: '趋势多少天淡一半（现值 7，中等易变）；调大=趋势判断留得久，调小=趋势很快过时。',
    group: 'background',
    control: 'slider',
    min: 1,
    max: 90,
    step: 1,
  },
  {
    path: 'background.halfLifeDays.trait',
    label: '半衰期·特质',
    hint: '特质多少天淡一半（现值 60，最稳最不易忘）；调大=特质几乎永不淡越发把人看死，调小=特质也慢慢淡忘但可能反复重学。',
    group: 'background',
    control: 'slider',
    min: 7,
    max: 365,
    step: 1,
  },
  {
    path: 'background.expireAfterDays.state',
    label: '过期·情绪状态',
    hint: '情绪距上次印证超 N 天就自然过期标失效（现值 7）；调大=情绪留得更久才失效，调小=很快被判过期清走。',
    group: 'background',
    control: 'slider',
    min: 1,
    max: 90,
    step: 1,
  },
  {
    path: 'background.expireAfterDays.hypothesis',
    label: '过期·假设',
    hint: '假设距上次印证超 N 天就过期失效（现值 14）；调大=旧假设赖得更久，调小=没印证的更快清掉。',
    group: 'background',
    control: 'slider',
    min: 1,
    max: 90,
    step: 1,
  },
  {
    path: 'background.expireAfterDays.trend',
    label: '过期·趋势',
    hint: '趋势距上次印证超 N 天就过期失效（现值 30）；调大=旧趋势留得更久，调小=趋势更快过期。',
    group: 'background',
    control: 'slider',
    min: 1,
    max: 180,
    step: 1,
  },
  {
    path: 'background.trendWindowDays',
    label: '趋势观察窗口',
    hint: '聚合趋势只看近多少天的状态（现值 14）；调大=趋势更稳但反应慢，调小=对新变化敏感但易把偶然当趋势。',
    group: 'background',
    control: 'slider',
    min: 3,
    max: 60,
    step: 1,
  },
  {
    path: 'background.trendMinCount',
    label: '趋势最少出现次数',
    hint: '窗口内同类状态至少出现几次才算趋势（现值 3）；调大=要出现很多次才算很稳但迟钝，调小=出现两次就当趋势灵敏但易草率。',
    group: 'background',
    control: 'slider',
    min: 2,
    max: 10,
    step: 1,
  },

  // ===== llm（温度，硬编码只读）=====
  {
    path: '_temperature',
    label: '模型温度',
    hint: '当前 0.3，写死在 src/llm/client.ts:85，本版不可调',
    control: 'readonly',
    group: 'llm',
  },
];
